name_eas = input("Enter your name: ")
age_eas = input("Enter your age: ")
course_eas = input("Enter your course: ")
university_eas = input("Enter your university: ")
print("\n----- STUDENT PROFILE -----")
print("Name:", name_eas)
print("Age:", age_eas)
print("Course:", course_eas)
print("University:", university_eas)
